extends Node
## Central signal hub. Systems talk through this bus so scenes stay decoupled.
## Signals are only emitted from other scripts, hence the warning suppression.
@warning_ignore_start("unused_signal")

signal tap_evaluated(result: Dictionary)
signal jackpot(multiplier: float, label: String)
signal near_miss(result: Dictionary)
signal miss(result: Dictionary)
signal perfect(result: Dictionary)
signal stage_cleared(stage_index: int, payout: int)
signal run_started()
signal run_ended(reason: String, stats: Dictionary)
signal revive_offered(result: Dictionary)
signal revive_resolved(success: bool)
signal energy_changed(amount: int, delta: int)
signal coins_changed(amount: int, delta: int)
signal dda_changed(profile: Dictionary)
signal zeigarnik_updated(loops: Array)
signal juice_hit(grade: String, intensity: float)
signal multiplier_changed(value: float)
signal meta_upgraded(stat: String, level: int)
signal ad_requested(placement: String, payload: Dictionary)
signal ad_finished(placement: String, rewarded: bool)
signal hold_started()
signal hold_released(held_seconds: float)
signal focus_changed(value: float)
signal countdown(step: int)
signal direction_flipped(direction: float)
signal session_changed()
